@ApiWebApp_HostAddress = http://localhost:5178

# Get all users
GET {{ApiWebApp_HostAddress}}/api/users
Accept: application/json
//Delete all Null Fields by include in repository method 11.09.2024
###

# Get user by ID
GET {{ApiWebApp_HostAddress}}/api/users/{id}
Accept: application/json

###

# Create a new user
POST {{ApiWebApp_HostAddress}}/api/users
Content-Type: application/json
Accept: application/json

{
  "firstName": "Meir",
  "LastName": "Shalom",
  
  "email": "Meir@example.com",
  "password": "1223Ad#21111",
  "confirmPassword": "1223Ad#21111",
  "phoneNumber": "1234567890",
  "role": "Reviewer"
}

###

# Update user by ID
PUT {{ApiWebApp_HostAddress}}/api/users/39b98f38-84e3-4801-9013-2adb5b4dad6f
Content-Type: application/json
Accept: application/json

{
  "firstName": "UpdatedFirstName",
  "lastName": "UpdatedLastName",
  "phoneNumber": "0987654321",
  "role": "Admin"
}

###

# Delete user by ID
DELETE {{ApiWebApp_HostAddress}}/api/users/1d933289-d80f-48b5-b5e2-fe70da578309
Accept: application/json


  ###

# Login
POST {{ApiWebApp_HostAddress}}/api/auth/login
Content-Type: application/json
Accept: application/json

{
  "username": "Meir@example.com",
  "password": "1223Ad#21111"
}