@ApiWebApp_HostAddress = http://localhost:5178

# Get all users
GET {{ApiWebApp_HostAddress}}/api/users
Accept: application/json
//Delete all Null Fields by include in repository method 11.09.2024
###

# Get user by ID
GET {{ApiWebApp_HostAddress}}/api/users/2837b9d5-d02f-40b3-ab76-b6195a2ba850
Accept: application/json

###

# Create a new user
POST {{ApiWebApp_HostAddress}}/api/users
Content-Type: application/json
Accept: application/json

{
  "firstName": "Michael",
  "lastName": "sss",   
  "email": "NMIN@alon.com",
  "password": "1223Ad#21111",
  "confirmPassword": "1223Ad#21111",
  "dateOfBirth": "1988-06-26",   
  "jobTitle": "Developer",
  "phoneNumber": "1234567890",
  "role": "Reviewer"
}

###

# Update user by ID
PUT {{ApiWebApp_HostAddress}}/api/users/2837b9d5-d02f-40b3-ab76-b6195a2ba850
Content-Type: application/json
Accept: application/json

{
  "firstName": "1UscpdategdFirstName",
  "lastName": "UpdatedLastName",
  "phoneNumber": "0987654321",
  
  "jobTitle": "UpdatedJobTitle"
  
}

###

# Delete user by ID
DELETE {{ApiWebApp_HostAddress}}/api/users/c7f2411a-8c46-4175-947b-52656e38cb0a


  ###

# Login
POST {{ApiWebApp_HostAddress}}/api/auth/login
Content-Type: application/json
Accept: application/json

{
  "username": "Aviho@Galili.com",
  "password": "1223Ad#21111"
}